(* auto-generated by gt *)
open Dump_ocaml;;
open Dump_gt_files;;

let i = ref 0;;

let progs = ref [];;

Array.iter( fun s -> 
	if(!i<>0) then (
		let parsed = 
			let lexbuf = Lexing.from_channel (open_in s) in
			Mlcf_parse.main Mlcf_lex.token lexbuf in
		  progs := parsed :: !progs
	); incr i
) Sys.argv;;

let progs = !progs;;

List.iter( fun parsed -> 
	     begin_dump parsed;
	     print_string "\n\n";
	     print_string "\n\n";
	) progs;;


let ss = List.map get_start_sym progs;;

dump_main ss;;
dump_gt_Make ss;;
